[[constraint]]
  name = "github.com/edganiukov/fcm"
  version = "0.3.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "~1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sideshow/apns2"
  version = "~0.14.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.9.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/franela/goblin"
  # version = "0.0.1"
  branch = "master"
